# Generated by Django 3.0.4 on 2020-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_bookloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='returned_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
